version: "3.9"
services:
  tire-model-Xception:
    image: tire-model-xception
  gateway:
    image: tire-model-xception-gateway
    environment:
      - TF_SERVING_HOST=tire-model-Xception:8500
    ports:
      - "9696:9696"